title = "RentHouse"
subtitle = "Для відпочинку"
description = "Найпопулярніші напрямки "
departures = {"kuiv": " з Києва", "lviw": " зі Львова", "odessa": " з Одеси", "chernivtsi": " з Чернівець",
              "chernigiv": " з Чернігова", "zakarpatte": "із Закарпаття", "ivan":"з Івано-Франківську"}

tours = {
    1: {
        "title": "Закарпаття",
        "description": "затишний готель.",
        "departure": "zakarpatte",
        "picture": "https://zahidkurort.com.ua/wp-content/themes/kurort/cache/45/03cd84cf64a6145_1013x532.jpg",
        "price": 6200,
        "stars": "4",
        "country": "Пилипець",
        "nights": 6,
        "date": "2 березня",
    },
    2: {
        "title": "Батяр",
        "description": "Будинок готелю має форму короткої літери U.",
        "departure": "lviw",
        "picture": "https://bukovel-hotel-ua.hotelmix.com.ua/data/Photos/OriginalPhoto/11709/1170996/1170996471/Bukovel-Hotel-Exterior.JPEG",
        "price": 8500,
        "stars": "5",
        "country": "Буковель",
        "nights": 8,
        "date": "12 січня",
    },
    3: {
        "title": "Ліжник",
        "description": "Готель з білого каменю",
        "departure": "odessa",
        "picture": "https://cf.bstatic.com/xdata/images/hotel/max500/266741392.jpg?k=8ca8f1ce6b54ff7d7bc5316c82f3d15aada16834b1b1108d8e79edca5d60c7b5&o=&hp=1",
        "price": 6300,
        "stars": "3",
        "country": "Косів",
        "nights": 11,
        "date": "7 лютого",
    },
    4: {
        "title": "Ведмежа",
        "description": "Красивий краєвид з вікна",
        "departure": "kuiv",
        "picture": "https://karpatskyi-teremok-dzembronia.hotelmix.com.ua/data/Photos/OriginalPhoto/12654/1265492/1265492017/Karpatskyi-Teremok-Exterior.JPEG",
        "price": 6200,
        "stars": "4",
        "country": "Космач",
        "nights": 9,
        "date": "22 жовтня",
    },
    5: {
        "title": "Сова",
        "description": "Розкішні апартаменти на березі водосховища",
        "departure": "chernivtsi",
        "picture": "https://pravda.if.ua/wp-content/uploads/2020/04/10827878_1539108119699451_4179360364797503328_o.jpg",
        "price": 6800,
        "stars": "4",
        "country": "Бакота",
        "nights": 8,
        "date": "18 вересня",
    },
    6: {
        "title": "Верховина",
        "description": "в центрі міста",
        "departure": "chernigiv",
        "picture": "https://static.karpaty.ua/uploads/house/55cc5c27c0557c2ebc003185/main_photo/big.jpg",
        "price": 5300,
        "stars": "3",
        "country": "Синевір",
        "nights": 13,
        "date": "15 серпня",
    },
    7: {
        "title": "Піп-Іван",
        "description": "З готелю близько до Чорногори",
        "departure": "odessa",
        "picture": "https://q-xx.bstatic.com/xdata/images/hotel/max500/300980475.jpg?k=a26871869739483c09ac4493f59c337ec2bc8acc5acd96d1b141b0f184399734&o=",
        "price": 7200,
        "stars": "5",
        "country": "Дземброня",
        "nights": 9,
        "date": "22 липня",
    },
    8: {
        "title": "Купель",
        "description": "термальні води",
        "departure": "kuiv",
        "picture": "https://turua.com.ua/upload/iblock/b6d/b6d7e9601f754931b633b8be6e10afd3.jpg",
        "price": 4400,
        "stars": "4",
        "country": "Велятино",
        "nights": 7,
        "date": "21 січня",
    },
    9: {
        "title": "Карпатський рай",
        "description": "Сучасний готель з видом на гори",
        "departure": "lviw",
        "picture": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/297878369.jpg?k=415eeb2d8faca7d2735b174728432b144e5bae2d2506f776012072af89214f8f&o=&hp=1",
        "price": 7800,
        "stars": "5",
        "country": "Яремче",
        "nights": 10,
        "date": "10 травня",
    },
    10: {
        "title": "Котедж у Карпатах",
        "description": "Затишний котедж з каміном та чудовим видом на гори.",
        "departure": "zakarpatte",
        "country": "Яремче",
        "picture": "https://ireland.apollo.olxcdn.com/v1/files/ggiktnu9kblv3-UA/image;s=2000x1335",
        "price": 3000,
        "stars": "4",
        "nights": 13,
        "date": "22 серпня",
    },
    11: {
        "title": "Будинок біля озера",
        "description": "Великий будинок з власним причалом.",
        "departure": "zakarpatte",
        "country": "Синевир",
        "picture": "https://cdn.riastatic.com/photos/dom/photo/29717/2971705/297170574/297170574xl.webp",
        "price": 5000,
        "nights": 11,
        "stars": "5",
        "date": "25 березня",
    },
    12: {
        "title": "Гірський котедж",
        "description": "Зручний котедж в тихому місці.",
        "country": "Косів",
        "departure": "ivan",
        "picture": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4Tw88aekYLVJv9YMrMGYVtJcAxojeUmAVag&s",
        "price": 2500,
        "stars": "4",
        "nights": 9,
        "date": "12 липня",
    },
    13: {
        "title": "Мисливський будинок",
        "description": "Будинок у лісі для справжніх мисливців.",
        "country": "Буковель",
        "departure": "ivan",
        "picture": "https://ireland.apollo.olxcdn.com/v1/files/e5cfu5h1ldpa-UA/image;s=1000x732",
        "price": 4000,
        "nights": 7,
        "stars": "4",
        "date": "11 квітня",
    },
    14: {
        "title": "Лісовий будинок",
        "description": "Будинок серед лісу для відпочинку від міського шуму.",
        "country": "Ворохта",
        "departure": "ivan",
        "picture": "https://i0.wp.com/photo-lviv.in.ua/wp-content/uploads/2022/09/03-2.jpg?ssl=1",
        "price": 3500,
        "nights": 13,
        "stars": "4",
        "date": "12 липня",
    },
    15: {
        "title": "Дім біля річки",
        "description": "Затишний будинок біля річки з чудовим видом.",
        "country": "Рахів",
        "departure": "zakarpatte",
        "picture": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/361053387.jpg?k=ba720dcd92ebd406a315e23f40d3af48f04832861bebc56050125474a57c4048&o=&hp=1",
        "price": 3200,
        "nights": 8,
        "stars": "4",
        "date": "21 червня",
    },
    16: {
        "title": "Великий котедж",
        "description": "Просторий котедж для великої компанії.",
        "country": "Драгобрат",
        "departure": "zakarpatte",
        "picture": "https://static.tildacdn.com/tild3033-3061-4039-a239-386366373537/Roman_Leonidov_publi.JPG",
        "price": 6000,
        "nights": 5,
        "stars": "4",
        "date": "30 квітня",
    },
    17: {
        "title": "Затишний будинок",
        "description": "Затишний будинок з каміном.",
        "departure": "lviw",
        "country": "Славське",
        "price": 6675,
        "stars": "4",
        "nights": 11,
        "date": "6 травня",
        "picture": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/558354384.jpg?k=08fffdb98199280745ec316270285c3edef700885401203ca307288c8eee1424&o=&hp=1",

    },
    19: {
        "title": "Будинок з садом в Чернівцях",
        "description": "Просторий будинок з великим садом і зоною для відпочинку.",
        "country": "Чернівці",
        "picture": "https://bukport.com/upload/000/u6/002/c6d3c425.jpg",
        "departure": "chernivtsi",
        "price": 3500,
        "nights": 7,
        "stars": "4",
        "date": "24 червня"
    },

}
